# syntax=docker/dockerfile:1
FROM ubuntu:20.04
ARG DEBIAN_FRONTEND=noninteractive

RUN useradd -m docker

RUN apt update -y && apt upgrade -y && apt install -y \
        sudo \
        curl\
        wget\
        lsb-release\
        software-properties-common\
        gnupg\
        build-essential \
        git \
        python3 \
        python3-venv \
        python3-dev \
        python3-pip \
        cmake \
        ninja-build \
        libboost-all-dev \
        doxygen \
        graphviz

RUN echo 'docker ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers

# USER docker

# Fix for the issue 
#  Error: fatal: detected dubious ownership in repository at '/__w/Shamrock/Shamrock/external/NVTX'
#  To add an exception for this directory, call:
#  	git config --global --add safe.directory /__w/Shamrock/Shamrock/external/NVTX
#  Unable to find current revision in submodule path 'external/NVTX'
#  Error: The process '/usr/bin/git' failed with exit code 1
#
# see : https://github.com/wmde/git-filter-repo-docker-action/pull/2/files
# T314987: Git require the .git folder to be owned by the same user
# 
# So we disable the check as detailled here
#https://stackoverflow.com/questions/71849415/i-cannot-add-the-parent-directory-to-safe-directory-in-git
#
RUN git config --global --add safe.directory '*'

# Sometime some apt repo fail on first attempt
# https://stackoverflow.com/questions/72644496/docker-container-connection-timeout-while-installing-packages
RUN echo '\
Acquire::Retries "20";\
Acquire::https::Timeout "60";\
Acquire::http::Timeout "60";\
' > /etc/apt/apt.conf.d/99custom

WORKDIR /home/docker
