name: Build push

on:
  push:

  schedule:
    # At 00:00 on Thursday.
    - cron:  '0 0 * * 4'

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository_owner }}
  

jobs:

  build-ubuntu_latest:

    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    uses: ./.github/workflows/build-and-push.yml
    with:
      imagename: shamrock-ci
      imagetag:  ubuntu-latest
      imagepath: ubuntu_latest
      runson: ubuntu-latest

  build-ubuntu_20:

    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    uses: ./.github/workflows/build-and-push.yml
    with:
      imagename: shamrock-ci
      imagetag:  ubuntu20
      imagepath: ubuntu20
      runson: ubuntu-latest

  build-ubuntu_22:

    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    uses: ./.github/workflows/build-and-push.yml
    with:
      imagename: shamrock-ci
      imagetag:  ubuntu22
      imagepath: ubuntu22
      runson: ubuntu-latest
            
  build-ubuntu_20_cuda_12:

    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    needs: [build-ubuntu_20]
    uses: ./.github/workflows/build-and-push.yml
    with:
      imagename: shamrock-ci
      imagetag:  ubuntu20cuda12
      imagepath: ubuntu20cuda12
      runson: self-hosted

  build-ubuntu_20_cuda_11:

    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
      
    needs: [build-ubuntu_20]
    uses: ./.github/workflows/build-and-push.yml
    with:
      imagename: shamrock-ci
      imagetag:  ubuntu20cuda11
      imagepath: ubuntu20cuda11
      runson: self-hosted

  build-ubuntu_22_cuda_12:

    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    needs: [build-ubuntu_22]
    uses: ./.github/workflows/build-and-push.yml
    with:
      imagename: shamrock-ci
      imagetag:  ubuntu22cuda12
      imagepath: ubuntu22cuda12
      runson: self-hosted

  build-ubuntu_22_cuda_11:

    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
      
    needs: [build-ubuntu_22]
    uses: ./.github/workflows/build-and-push.yml
    with:
      imagename: shamrock-ci
      imagetag:  ubuntu22cuda11
      imagepath: ubuntu22cuda11
      runson: self-hosted
  
  build-ubuntu_20_rocm543:

    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
      
    needs: [build-ubuntu_20]
    uses: ./.github/workflows/build-and-push.yml
    with:
      imagename: shamrock-ci
      imagetag:  ubuntu20rocm543
      imagepath: ubuntu20rocm5.4.3
      runson: ubuntu-latest
      
  build-ubuntu_22_rocm543:

    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
      
    needs: [build-ubuntu_22]
    uses: ./.github/workflows/build-and-push.yml
    with:
      imagename: shamrock-ci
      imagetag:  ubuntu22rocm543
      imagepath: ubuntu22rocm5.4.3
      runson: ubuntu-latest
      
  build-ubuntu_20_dpcpp_cuda12:

    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
      
    needs: [build-ubuntu_20_cuda_12]
    uses: ./.github/workflows/build-and-push.yml
    with:
      imagename: shamrock-ci      
      imagetag:  ubuntu20cuda12dpcpp
      imagepath: ubuntu20dpcpp_cuda12
      runson: self-hosted

  build-ubuntu_22_dpcpp_cuda12:

    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
      
    needs: [build-ubuntu_22_cuda_12]
    uses: ./.github/workflows/build-and-push.yml
    with:
      imagename: shamrock-ci      
      imagetag:  ubuntu22cuda12dpcpp
      imagepath: ubuntu22dpcpp_cuda12
      runson: self-hosted

  build-ubuntu_20_dpcpp_rocm543:

    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
      
    needs: [build-ubuntu_20_rocm543]
    uses: ./.github/workflows/build-and-push.yml
    with:
      imagename: shamrock-ci      
      imagetag:  ubuntu20rocm543dpcpp
      imagepath: ubuntu20dpcpp_rocm5.4.3
      runson: self-hosted

  build-ubuntu_22_dpcpp_rocm543:

    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
      
    needs: [build-ubuntu_22_rocm543]
    uses: ./.github/workflows/build-and-push.yml
    with:
      imagename: shamrock-ci      
      imagetag:  ubuntu22rocm543dpcpp
      imagepath: ubuntu22dpcpp_rocm5.4.3
      runson: self-hosted
